prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/credentials/google_authentication.sql
@@application/shared_components/navigation/lists/navigation.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/automated_testing_job.sql
@@application/shared_components/navigation/lists/utilities.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/preferences.sql
@@application/shared_components/navigation/lists/code_tables.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/permalink_page_auth.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/application_sentry.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/standard_tests.sql
@@application/shared_components/logic/application_processes/set_time_zone.sql
@@application/shared_components/logic/application_processes/trim_all_page_items.sql
@@application/shared_components/logic/application_items/application_title.sql
@@application/shared_components/logic/application_items/apx_bldr_session.sql
@@application/shared_components/logic/application_items/a_num_apps.sql
@@application/shared_components/logic/application_items/a_num_stds.sql
@@application/shared_components/logic/application_items/last_view.sql
@@application/shared_components/logic/application_computations/apx_bldr_session.sql
@@application/shared_components/logic/application_computations/a_num_stds.sql
@@application/shared_components/logic/application_computations/a_num_apps.sql
@@application/shared_components/logic/application_computations/application_title.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_control_scope.sql
@@application/shared_components/user_interface/lovs/access_control_scope1.sql
@@application/shared_components/user_interface/lovs/access_levels.sql
@@application/shared_components/user_interface/lovs/application_statuses.sql
@@application/shared_components/user_interface/lovs/application_types.sql
@@application/shared_components/user_interface/lovs/notification_type.sql
@@application/shared_components/user_interface/lovs/open_status.sql
@@application/shared_components/user_interface/lovs/range_demo.sql
@@application/shared_components/user_interface/lovs/rows.sql
@@application/shared_components/user_interface/lovs/standards.sql
@@application/shared_components/user_interface/lovs/standard_status_ranges.sql
@@application/shared_components/user_interface/lovs/test_link_types.sql
@@application/shared_components/user_interface/lovs/test_types.sql
@@application/shared_components/user_interface/lovs/timeframe_2_weeks.sql
@@application/shared_components/user_interface/lovs/username_format.sql
@@application/shared_components/user_interface/lovs/yes_no.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/google.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_minicalendar.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_status.sql
@@application/shared_components/plugins/region_type/com_oracle_auth_administration.sql
@@application/shared_components/plugins/item_type/com_oracle_apex_flex_field.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_acl_warning.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_translated_message.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_tag_cloud.sql
@@application/shared_components/plugins/item_type/com_oracle_apex_simple_checkbox.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00039.sql
@@application/pages/page_00042.sql
@@application/pages/page_00045.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00092.sql
@@application/pages/page_00101.sql
@@application/pages/page_00175.sql
@@application/pages/page_00700.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/deployment/definition.sql
@@application/deployment/install/upgrade_drop_files_table.sql
@@application/deployment/install/install_set_plscope_settings.sql
@@application/deployment/install/upgrade_table_modifications_for_test_types.sql
@@application/deployment/install/install_eba_stds_spec.sql
@@application/deployment/install/upgrade_test_validations_table.sql
@@application/deployment/install/install_eba_stds_security_spec.sql
@@application/deployment/install/upgrade_eba_stds_standard_statuses.sql
@@application/deployment/install/upgrade_eba_stds_parser_spec.sql
@@application/deployment/install/install_framework_spec.sql
@@application/deployment/install/install_parser_spec.sql
@@application/deployment/install/upgrade_eba_stds_parser_body.sql
@@application/deployment/install/install_filter_search_spec.sql
@@application/deployment/install/upgrade_sample_data_package_body.sql
@@application/deployment/install/upgrade_reload_sample_data.sql
@@application/deployment/install/install_sequences.sql
@@application/deployment/install/install_tags_tables.sql
@@application/deployment/install/upgrade_eba_stds_spec.sql
@@application/deployment/install/install_acl_tables.sql
@@application/deployment/install/upgrade_eba_stds_body.sql
@@application/deployment/install/upgrade_drop_released_in_version.sql
@@application/deployment/install/install_error_table.sql
@@application/deployment/install/upgrade_drop_old_filter_package.sql
@@application/deployment/install/upgrade_filter_search_spec.sql
@@application/deployment/install/upgrade_filter_search_body.sql
@@application/deployment/install/install_timezone_table.sql
@@application/deployment/install/install_history_table.sql
@@application/deployment/install/upgrade_missing_indexes.sql
@@application/deployment/install/upgrade_add_flex_columns.sql
@@application/deployment/install/install_notifications_table.sql
@@application/deployment/install/install_application_tables.sql
@@application/deployment/install/upgrade_flex_registry_table_and_trigger.sql
@@application/deployment/install/install_application_triggers.sql
@@application/deployment/install/upgrade_flex_page_map_table_and_trigger.sql
@@application/deployment/install/upgrade_flex_static_lovs_table_and_trigger.sql
@@application/deployment/install/install_history_triggers.sql
@@application/deployment/install/upgrade_flex_framework_package_spec.sql
@@application/deployment/install/install_eba_stds_body.sql
@@application/deployment/install/upgrade_flex_framework_package_body.sql
@@application/deployment/install/install_framework_body.sql
@@application/deployment/install/install_parser_body.sql
@@application/deployment/install/upgrade_populate_flex_registry.sql
@@application/deployment/install/install_filter_search_body.sql
@@application/deployment/install/upgrade_populate_flex_page_map.sql
@@application/deployment/install/upgrade_framework_spec.sql
@@application/deployment/install/install_eba_stds_security_body.sql
@@application/deployment/install/upgrade_framework_body.sql
@@application/deployment/install/install_install_acl_data.sql
@@application/deployment/install/upgrade_export_package.sql
@@application/deployment/install/upgrade_export_package_body.sql
@@application/deployment/install/install_sample_data_package_spec.sql
@@application/deployment/install/install_sample_data_package_body.sql
@@application/deployment/install/upgrade_set_first_run_preference.sql
@@application/deployment/install/install_initial_data_load.sql
@@application/deployment/install/install_add_flex_columns.sql
@@application/deployment/install/install_flex_registry_table_and_trigger.sql
@@application/deployment/install/install_flex_page_map_table_and_trigger.sql
@@application/deployment/install/install_flex_static_lovs_table_and_trigger.sql
@@application/deployment/install/install_flex_framework_package_spec.sql
@@application/deployment/install/install_flex_framework_package_body.sql
@@application/deployment/install/install_populate_flex_registry.sql
@@application/deployment/install/install_populate_flex_page_map.sql
@@application/deployment/install/install_export_package.sql
@@application/deployment/install/install_export_package_body.sql
@@application/deployment/install/install_set_first_run_preference.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
